# For condition grammar see: https://docs.mergify.com/conditions/#grammar

queue_rules:
  - name: default
    conditions:
      #- "#approved-reviews-by>=1"
      - "label=ready-to-merge"
      - "check-success=tests"

pull_request_rules:
  - name: main - Add to merge queue on approval
    conditions:
      #- "#approved-reviews-by>=1"
      - "-draft"  # Never queue up drafts
      - "label=ready-to-merge"  # Require label
      - "base=main"  # Filter branches by name
    actions:
      queue:
        method: squash

  - name: develop branches - Add to merge queue on approval
    conditions:
      #- "#approved-reviews-by>=1"
      - "-draft"  # Never queue up drafts
      - "label=ready-to-merge"  # Require label
      - "base~=^develop"  # Filter branches by name
    actions:
      queue:
        method: squash

  - name: Automatic PR branch updates
    conditions:
      - "queue-position=-1"  # Not queued
    actions:
      update:

  - name: Clean up after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
      label:
        remove:
          - "ready-to-merge"

  - name: Add label on test failures
    conditions:
      - or:
        - check-failure=tests
        - check-skipped=tests
    actions:
      label:
        add:
          - "tests-failing"

  - name: Remove label on test success
    conditions:
      - check-success=tests
    actions:
      label:
        remove:
          - "tests-failing"

  - name: Toggle label on merge conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - "merge-conflicts"