# For condition grammar see: https://docs.mergify.com/conditions/#grammar

pull_request_rules:
  - name: main - Automatic merge on approval
    conditions:
      #- "#approved-reviews-by>=1"
      - "-draft"  # Never queue up drafts
      - "label=ready-to-merge"  # Require label
      - "base=main"  # Filter branches by name
    actions:
      queue:
        method: squash
  
  - name: develop branches - Automatic merge on approval
    conditions:
      #- "#approved-reviews-by>=1"
      - "-draft"  # Never queue up drafts
      - "label=ready-to-merge"  # Require label
      - "base~=^develop"  # Filter branches by name
    actions:
      queue:
        method: squash
        
  - name: Automatic PR branch updates
    conditions:
      - "queue-position=-1"  # Not queued
    actions:
      update:
      
  - name: Delete PR head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:

queue_rules:
  - name: default
    conditions:
      #- "#approved-reviews-by>=1"
      - "label=ready-to-merge"
