# Copyright 2010 New Relic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Deploy

on:
  release:
    types:
      - published

jobs:
  build-py3:
    strategy:
      matrix:
        include:
            # Linux glibc
            - wheel: cp37-manylinux
              os: ubuntu-latest
            - wheel: cp38-manylinux
              os: ubuntu-latest
            - wheel: cp39-manylinux
              os: ubuntu-latest
            - wheel: cp310-manylinux
              os: ubuntu-latest
            - wheel: cp311-manylinux
              os: ubuntu-latest
            - wheel: cp312-manylinux
              os: ubuntu-latest
            # Linux musllibc
            - wheel: cp37-musllinux
              os: ubuntu-latest
            - wheel: cp38-musllinux
              os: ubuntu-latest
            - wheel: cp39-musllinux
              os: ubuntu-latest
            - wheel: cp310-musllinux
              os: ubuntu-latest
            - wheel: cp311-musllinux
              os: ubuntu-latest
            - wheel: cp312-musllinux
              os: ubuntu-latest
            # MacOS x86
            - wheel: cp36-macosx_x86_64
              os: macos-13
            - wheel: cp37-macosx_x86_64
              os: macos-13
            - wheel: cp38-macosx_x86_64
              os: macos-13
            - wheel: cp39-macosx_x86_64
              os: macos-13
            - wheel: cp310-macosx_x86_64
              os: macos-13
            - wheel: cp311-macosx_x86_64
              os: macos-13
            - wheel: cp312-macosx_x86_64
              os: macos-13
            # MacOS ARM
            - wheel: cp38-macosx_arm64
              os: macos-14
            - wheel: cp39-macosx_arm64
              os: macos-14
            - wheel: cp310-macosx_arm64
              os: macos-14
            - wheel: cp311-macosx_arm64
              os: macos-14
            - wheel: cp312-macosx_arm64
              os: macos-14
            # Windows
            - wheel: cp36-win
              os: windows-latest
            - wheel: cp37-win
              os: windows-latest
            - wheel: cp38-win
              os: windows-latest
            - wheel: cp39-win
              os: windows-latest
            - wheel: cp310-win
              os: windows-latest
            - wheel: cp311-win
              os: windows-latest
            - wheel: cp312-win
              os: windows-latest

    name: Build wheels for ${{ matrix.wheel }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # 3.0.0

      - name: Build Wheels
        uses: pypa/cibuildwheel@bd033a44476646b606efccdd5eed92d5ea1d77ad # 2.20.0
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: "${{ matrix.wheel }}*"
          CIBW_ARCHS_LINUX: x86_64 aarch64
          CIBW_ARCHS_MACOS: native
          CIBW_ARCHS_WINDOWS: AMD64 ARM64
          CIBW_ENVIRONMENT_LINUX: "LD_LIBRARY_PATH=/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/usr/local/lib64:/usr/local/lib"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "PYTHONPATH={project}/tests pytest {project}/tests/agent_unittests -vx"

      - name: Upload Artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # 4.3.1
        with:
          name: cibw-${{ matrix.os }}-${{ matrix.wheel }}
          path: ./wheelhouse/*.whl
          retention-days: 1

  build-py2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # 3.0.0

      - name: Build Wheels
        uses: pypa/cibuildwheel@bf3a5590c9aeb9a7e4ff4025ef7400e0c6ad1248 # 1.12.0  (Last release to support Python 2)
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: cp27-manylinux_x86_64
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ENVIRONMENT: "LD_LIBRARY_PATH=/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/usr/local/lib64:/usr/local/lib"
          CIBW_TEST_REQUIRES: pytest==4.6.11
          CIBW_TEST_COMMAND: "PYTHONPATH={project}/tests pytest {project}/tests/agent_unittests -vx"

      - name: Upload Artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # 4.3.1
        with:
          name: cibw-${{ github.job }}
          path: ./wheelhouse/*.whl
          retention-days: 1

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          pip install -U pip
          pip install -U setuptools

      - name: Build Source Package
        run: |
          python setup.py sdist

      - name: Prepare MD5 Hash File
        run: |
          tarball="$(python setup.py --fullname).tar.gz"
          md5_file=${tarball}.md5
          openssl md5 -binary dist/${tarball} | xxd -p | tr -d '\n' > dist/${md5_file}

      - name: Upload Artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # 4.3.1
        with:
          name: cibw-${{ github.job }}-sdist
          path: |
            ./dist/*.tar.gz
            ./dist/*.tar.gz.md5
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    
    needs:
      - build-py3
      - build-py2
      - build-sdist

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Upload Package to S3
        run: |
          tarball="$(python setup.py --fullname).tar.gz"
          md5_file=${tarball}.md5
          aws s3 cp dist/${md5_file} $S3_DST/${md5_file}
          aws s3 cp dist/${tarball} $S3_DST/${tarball}
        env:
          S3_DST: s3://nr-downloads-main/python_agent/release
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2

      - uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # 1.9.0
